/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JSpinner;

/**
 *
 * @author rodrigo valdes
 */
public class EscogerFecha extends javax.swing.JDialog {

    /**
     * Creates new form EscogerFecha
     */
    public EscogerFecha(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    // Getter del spinner para poder sacar el valor elegido al volver al parent
    public JSpinner getjSpinner_fecha() {
        return jSpinner_fecha;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner_fecha = new javax.swing.JSpinner();
        jButton_aceptarFecha = new javax.swing.JButton();
        jL_eligeFecha = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jSpinner_fecha.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jSpinner_fecha.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, new java.util.Date(), java.util.Calendar.DAY_OF_MONTH));
        jSpinner_fecha.setToolTipText("Fecha seleccionada");

        jButton_aceptarFecha.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jButton_aceptarFecha.setForeground(new java.awt.Color(0, 102, 102));
        jButton_aceptarFecha.setText("Aceptar");
        jButton_aceptarFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_aceptarFechaActionPerformed(evt);
            }
        });

        jL_eligeFecha.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        jL_eligeFecha.setForeground(new java.awt.Color(0, 102, 102));
        jL_eligeFecha.setText("Selecciona una fecha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jL_eligeFecha)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSpinner_fecha)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_aceptarFecha)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jL_eligeFecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_aceptarFecha)
                    .addComponent(jSpinner_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_aceptarFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_aceptarFechaActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_jButton_aceptarFechaActionPerformed

 
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_aceptarFecha;
    private javax.swing.JLabel jL_eligeFecha;
    private javax.swing.JSpinner jSpinner_fecha;
    // End of variables declaration//GEN-END:variables
}
